# Define the workflow name
name: Test Workflow

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

# Define the workflow jobs
jobs:
  test_job:
    name: Running Test Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.5.0
      with:
        username: 'lourorafael'
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        context: . #dockerfile path (in this case is on the root)
        tags: 'lourorafael/fiat-ghactions:latest'
        push: true
